### ISSUE TITLE
What if no DNS?

### ISSUE THREAD

**Issue by vallard** [zedtux/nginx-proxy#11]
If I don't have DNS, but I'm just using the IP addresses internally, can I just set VIRTUAL_HOST=* in my docker registry container?  I'm trying that and it isn't working so wondering if there is anyway I can still do this.  
(PS: I only have one virtual host I need)

Thanks!

**Comment by zedtux** [comment]
The original nginx-proxy from jwilder has been built on the fact that you have DNS names and you want to host mulitple services on the same host. This fork follow the same principle so no it's not possible.

You should fork the project and change it in order to cover your case as in my opinion it would be very hard to support both (IP and DNS).

**Comment by vallard** [comment]
That makes sense.  I think I understand it now and for what use cases its for.  I'll have to find another solution for what I'm looking to do.  Appreciate the quick response.
